### ISSUE TITLE
Cmake fails when -DOGL_USE_EXTERNAL_GINKGO=On is set

### ISSUE THREAD

**Issue by greole** [greole/OGL#5]
See title, building with cmake when setting ` -DOGL_USE_EXTERNAL_GINKGO=On` . The relevant error message is as follows

```
CMake Error at /home/go/data/code/ginkgo/cmake/Modules/FindHWLOC.cmake:124 (add_library):
  add_library cannot create imported target "hwloc" because another target
  with the same name already exists.
Call Stack (most recent call first):
  /usr/local/lib/cmake/Ginkgo/GinkgoConfig.cmake:185 (find_package)
  CMakeLists.txt:27 (find_package)
```

**Comment by tcojean** [comment]
That's interesting, if I understand there is some mixed setup as well where the installed GinkgoConfig.cmake uses the module from the Ginkgo source? That should change with https://github.com/ginkgo-project/ginkgo/pull/745 but I don't think that should fix the problem. I will fix it as part of this PR.
